---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: carshop
  name: mongodb-carshop
  namespace: carshop
spec:
  selector:
    matchLabels:
      app: carshop
  template:
    metadata:
      labels:
        app: carshop
    spec:
      containers:
      - name: mongodb-carshop
        image: mongo:latest
        ports:
        - containerPort: 27017

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: carshop
  name: mongodb-carshop-svc
  namespace: carshop
spec:
  selector:
    app: carshop
  ports:
    - name: mongodb-carshop-svc
      port: 27017
      protocol: TCP
      targetPort: 27017
