apiVersion: v1
kind: Service
metadata:
  name: carshop-svc
  namespace: carshop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:account_id:certificate/id
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    svc: carshop-svc
  ports:
  - name: http
    port: 80
    targetPort: 3001
  - name: https
    port: 443
    targetPort: 3001
  type: LoadBalancer
